[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"

[features]
seeds = false
skip-lint = false

# [programs.localnet]
# raydium_cp_swap = "soTGt6rjUYJjZ1Fxa65wPjehiYvNDDYkY4wvDjyyoW6"

# [registry]
# url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/visheshsachdev/.config/solana/team.json"

[workspace]
members = ["programs/cp-swap"]
