[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.20"

[features]
seeds = false
skip-lint = false

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=7293b92a-03dd-435c-b594-e754264f781a"
wallet = "/Users/visheshsachdev/.config/solana/id.json"

[workspace]
members = ["programs/cpmm-lp-lock"]
